-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.request_services
(
    id integer NOT NULL DEFAULT nextval('request_services_id_seq'::regclass),
    name character varying COLLATE pg_catalog."default",
    email character varying COLLATE pg_catalog."default",
    phone integer,
    is_finished boolean,
    track_type_id bigint,
    service_type_id bigint,
    created_at timestamp without time zone,
    updated_at timestamp without time zone,
    CONSTRAINT request_services_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.service_types
(
    id integer NOT NULL DEFAULT nextval('service_types_id_seq'::regclass),
    name character varying COLLATE pg_catalog."default",
    description character varying COLLATE pg_catalog."default",
    created_at timestamp without time zone,
    updated_at timestamp without time zone,
    CONSTRAINT service_types_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.track_types
(
    id integer NOT NULL DEFAULT nextval('track_types_id_seq'::regclass),
    name character varying COLLATE pg_catalog."default",
    description character varying COLLATE pg_catalog."default",
    created_at timestamp without time zone,
    updated_at timestamp without time zone,
    CONSTRAINT track_types_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.users
(
    id integer NOT NULL DEFAULT nextval('users_id_seq'::regclass),
    name character varying COLLATE pg_catalog."default",
    email character varying COLLATE pg_catalog."default",
    password character varying COLLATE pg_catalog."default",
    created_at timestamp without time zone,
    updated_at timestamp without time zone,
    CONSTRAINT users_pkey PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS public.request_services
    ADD CONSTRAINT request_services_service_type_id_fkey FOREIGN KEY (service_type_id)
    REFERENCES public.service_types (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.request_services
    ADD CONSTRAINT request_services_track_type_id_fkey FOREIGN KEY (track_type_id)
    REFERENCES public.track_types (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

END;